#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.7
# In conjunction with Tcl version 8.6
#    Sep 13, 2016 04:43:37 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import manage_occupancies_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Manage_Occupancies (root)
    manage_occupancies_support.init(root, top)
    root.mainloop()

w = None
def create_Manage_Occupancies(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Manage_Occupancies (w)
    manage_occupancies_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Manage_Occupancies():
    global w
    w.destroy()
    w = None


class Manage_Occupancies:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = 'wheat'  # X11 color: #f5deb3
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "TkDefaultFont"

        top.geometry("600x450+939+285")
        top.title("Manage_Occupancies")
        top.configure(background="#8080c0")
        top.configure(highlightbackground="wheat")
        top.configure(highlightcolor="black")

        self.Button1 = Button(top)
        self.Button1.place(relx=0.25, rely=0.56, height=30, width=278)
        self.Button1.configure(activebackground="#f4bcb2")
        self.Button1.configure(activeforeground="black")
        self.Button1.configure(background="#f5f5dedeb3b3")
        self.Button1.configure(command=lambda:manage_occupancies_support.GenOccupancyFile())
        self.Button1.configure(disabledforeground="#b8a786")
        font10 = "-family Arial -size 12 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="wheat")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''generate occupancy file''')
        self.Button1.configure(width=278)

        self.Button2 = Button(top)
        self.Button2.place(relx=0.75, rely=0.76, height=30, width=55)
        self.Button2.configure(activebackground="#f4bcb2")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background=_bgcolor)
        self.Button2.configure(command=lambda:manage_occupancies_support.destroy_window())
        self.Button2.configure(disabledforeground="#b8a786")
        self.Button2.configure(font=font10)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="wheat")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Close''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.25, rely=0.22, height=137, width=293)
        self.Label1.configure(activebackground="#ffffcd")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor=W)
        self.Label1.configure(background=_bgcolor)
        self.Label1.configure(disabledforeground="#b8a786")
        self.Label1.configure(font=font10)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="wheat")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Place Occupancy Managment Dialog Here''')




if __name__ == '__main__':
    vp_start_gui()



