#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Sep 13, 2016 05:25:46 PM


set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#8080c0} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+578+182
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 104 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Manage_Contacts"
    ttk::style configure Button -background wheat
    ttk::style configure Button -foreground #000000
    ttk::style configure Button -font TkDefaultFont
    button $top.but34 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#f5f5dedeb3b3} -command lambda:GenOccupancyFile() \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -pady 0 \
        -text {generate occupancy file} 
    vTcl:DefineAlias "$top.but34" "Button1" vTcl:WidgetProc "$top" 1
    button $top.but35 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command lambda:master.destroy() -disabledforeground {#b8a786} \
        -font font10 -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -pady 0 -text Close 
    vTcl:DefineAlias "$top.but35" "Button2" vTcl:WidgetProc "$top" 1
    label $top.lab36 \
        -activebackground {#ffffcd} -activeforeground black -anchor w \
        -background wheat -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Label -textvariable self.instance 
    vTcl:DefineAlias "$top.lab36" "Label1" vTcl:WidgetProc "$top" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but34 \
        -in $top -x 150 -y 250 -width 278 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.but35 \
        -in $top -x 450 -y 340 -anchor nw -bordermode ignore 
    place $top.lab36 \
        -in $top -x 150 -y 100 -width 273 -height 137 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

