#############################################################################
# Generated by PAGE version 4.7
# in conjunction with Tcl version 8.6
#    Nov 25, 2016 12:24:59 AM


set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top34
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.fra37
    set site_3_0 $base.fra61
    set site_3_0 $base.fra68
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top34 {base} {
    if {$base == ""} {
        set base .top34
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#8080c0} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+459+132
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 104 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "ZMC_Input_Controls"
    ttk::style configure Button -background wheat
    ttk::style configure Button -foreground #000000
    ttk::style configure Button -font TkDefaultFont
    button $top.but34 \
        -activebackground {#f4bcb2} -activeforeground black \
        -background {#f5f5dedeb3b3} -command lambda:GenOccupancyFile() \
        -disabledforeground {#b8a786} -font font10 -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -pady 0 \
        -text {generate ZMC input file} 
    vTcl:DefineAlias "$top.but34" "Button1" vTcl:WidgetProc "$top" 1
    button $top.but35 \
        -activebackground {#f4bcb2} -activeforeground black -background wheat \
        -command lambda:master.destroy() -disabledforeground {#b8a786} \
        -font font10 -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -pady 0 -text Close 
    vTcl:DefineAlias "$top.but35" "Button2" vTcl:WidgetProc "$top" 1
    label $top.lab36 \
        -activebackground {#ffffcd} -activeforeground black -anchor w \
        -background wheat -disabledforeground {#b8a786} -font font10 \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -text Label -textvariable self.instance 
    vTcl:DefineAlias "$top.lab36" "Label1" vTcl:WidgetProc "$top" 1
    frame $top.fra37 \
        -borderwidth 2 -relief groove -background wheat -height 225 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 155 
    vTcl:DefineAlias "$top.fra37" "Frame1" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra37
    entry $site_3_0.ent38 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_Temp 
    vTcl:DefineAlias "$site_3_0.ent38" "Entry1" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent39 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_cycles 
    vTcl:DefineAlias "$site_3_0.ent39" "Entry2" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab40 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Temp 
    vTcl:DefineAlias "$site_3_0.lab40" "Label2" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {MC Cycles} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label3" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {X's shift width} 
    vTcl:DefineAlias "$site_3_0.lab44" "Label4" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Q's shift width} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label5" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {In's width} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label6" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text XYZinitwidth 
    vTcl:DefineAlias "$site_3_0.lab47" "Label7" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text QInitWidth 
    vTcl:DefineAlias "$site_3_0.lab48" "Label8" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text InInitW 
    vTcl:DefineAlias "$site_3_0.lab49" "Label9" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text IncUpdate 
    vTcl:DefineAlias "$site_3_0.lab50" "Label10" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text BAdjust 
    vTcl:DefineAlias "$site_3_0.lab51" "Label11" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_XYZ_width 
    vTcl:DefineAlias "$site_3_0.ent52" "Entry3" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent53 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_Q_width 
    vTcl:DefineAlias "$site_3_0.ent53" "Entry4" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent54 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_In_width 
    vTcl:DefineAlias "$site_3_0.ent54" "Entry5" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_XYZ_init_width 
    vTcl:DefineAlias "$site_3_0.ent55" "Entry6" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_Q_Init_Width 
    vTcl:DefineAlias "$site_3_0.ent56" "Entry7" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent57 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_InInitW 
    vTcl:DefineAlias "$site_3_0.ent57" "Entry8" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent58 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_IncUpdate 
    vTcl:DefineAlias "$site_3_0.ent58" "Entry9" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_BAdjust 
    vTcl:DefineAlias "$site_3_0.ent59" "Entry10" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_BAdjust_Biso 
    vTcl:DefineAlias "$site_3_0.ent60" "Entry11" vTcl:WidgetProc "$top" 1
    place $site_3_0.ent38 \
        -in $site_3_0 -x 83 -y 12 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent39 \
        -in $site_3_0 -x 83 -y 34 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 5 -y 13 -width 41 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 6 -y 34 -width 61 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 2 -y 56 -width 81 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 6 -y 75 -width 71 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 4 -y 95 -width 61 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 3 -y 115 -width 71 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 8 -y 136 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 5 -y 156 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 5 -y 177 -width 61 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 5 -y 199 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 83 -y 55 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent53 \
        -in $site_3_0 -x 83 -y 76 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent54 \
        -in $site_3_0 -x 83 -y 96 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 83 -y 116 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent56 \
        -in $site_3_0 -x 83 -y 136 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 83 -y 156 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 83 -y 178 -width 64 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 83 -y 199 -width 24 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 111 -y 199 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    text $top.tex42 \
        -background white -font TkTextFont -foreground black -height 76 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 294 -wrap word 
    .top34.tex42 configure -font TkTextFont
    .top34.tex42 insert end text
    vTcl:DefineAlias "$top.tex42" "Text1" vTcl:WidgetProc "$top" 1
    button $top.but43 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -command Run_ZMC -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground wheat \
        -highlightcolor black -pady 0 -text {Run ZMC} 
    vTcl:DefineAlias "$top.but43" "Button3" vTcl:WidgetProc "$top" 1
    frame $top.fra61 \
        -borderwidth 2 -relief groove -background wheat -height 75 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 155 
    vTcl:DefineAlias "$top.fra61" "Frame2" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra61
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text NumZMATs 
    vTcl:DefineAlias "$site_3_0.lab62" "Label12" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text NumLoc 
    vTcl:DefineAlias "$site_3_0.lab63" "Label13" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab64 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text NumSprings 
    vTcl:DefineAlias "$site_3_0.lab64" "Label14" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent65 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_nZmats 
    vTcl:DefineAlias "$site_3_0.ent65" "Entry12" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent66 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_nLoc 
    vTcl:DefineAlias "$site_3_0.ent66" "Entry13" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent67 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable ZMC_Nspring 
    vTcl:DefineAlias "$site_3_0.ent67" "Entry14" vTcl:WidgetProc "$top" 1
    place $site_3_0.lab62 \
        -in $site_3_0 -x 3 -y 4 -width 71 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 5 -y 25 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 10 -y 47 -width 61 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 81 -y 4 -width 54 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent66 \
        -in $site_3_0 -x 81 -y 26 -width 54 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent67 \
        -in $site_3_0 -x 81 -y 48 -width 54 -height 19 -anchor nw \
        -bordermode ignore 
    frame $top.fra68 \
        -borderwidth 2 -relief groove -background wheat -height 165 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 195 
    vTcl:DefineAlias "$top.fra68" "Frame3" vTcl:WidgetProc "$top" 1
    set site_3_0 $top.fra68
    label $site_3_0.lab70 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Moulation Type} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label15" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Q-Vector 
    vTcl:DefineAlias "$site_3_0.lab71" "Label16" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text Q-Amplitude 
    vTcl:DefineAlias "$site_3_0.lab72" "Label17" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab73 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text Q-Polarization 
    vTcl:DefineAlias "$site_3_0.lab73" "Label18" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text {Q-ZOCC } 
    vTcl:DefineAlias "$site_3_0.lab74" "Label19" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text QDIR 
    vTcl:DefineAlias "$site_3_0.lab75" "Label20" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent76 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QModType 
    vTcl:DefineAlias "$site_3_0.ent76" "Entry15" vTcl:WidgetProc "$top" 1
    entry $site_3_0.ent78 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QVEC1 
    vTcl:DefineAlias "$site_3_0.ent78" "Entry16" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd79 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QVEC2 
    vTcl:DefineAlias "$site_3_0.cpd79" "Entry17" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd80 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QVEC3 
    vTcl:DefineAlias "$site_3_0.cpd80" "Entry18" vTcl:WidgetProc "$top" 1
    label $site_3_0.lab82 \
        -activebackground {#f9f9f9} -activeforeground black -background wheat \
        -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text QCONC 
    vTcl:DefineAlias "$site_3_0.lab82" "Label21" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd83 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QPOL1 
    vTcl:DefineAlias "$site_3_0.cpd83" "Entry20" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd84 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QPOL2 
    vTcl:DefineAlias "$site_3_0.cpd84" "Entry21" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd85 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QPOL3 
    vTcl:DefineAlias "$site_3_0.cpd85" "Entry22" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd86 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QZOCC 
    vTcl:DefineAlias "$site_3_0.cpd86" "Entry23" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd87 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QCONC 
    vTcl:DefineAlias "$site_3_0.cpd87" "Entry24" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd88 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QDIR1 
    vTcl:DefineAlias "$site_3_0.cpd88" "Entry25" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd89 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QDIR2 
    vTcl:DefineAlias "$site_3_0.cpd89" "Entry26" vTcl:WidgetProc "$top" 1
    entry $site_3_0.cpd90 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QDIR3 
    vTcl:DefineAlias "$site_3_0.cpd90" "Entry27" vTcl:WidgetProc "$top" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 7 -y 10 -width 91 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 11 -y 36 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab72 \
        -in $site_3_0 -x 8 -y 62 -width 61 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 7 -y 86 -width 71 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab74 \
        -in $site_3_0 -x 11 -y 109 -width 51 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab75 \
        -in $site_3_0 -x 19 -y 133 -width 31 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent76 \
        -in $site_3_0 -x 97 -y 10 -width 44 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent78 \
        -in $site_3_0 -x 67 -y 37 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd79 \
        -in $site_3_0 -x 106 -y 37 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd80 \
        -in $site_3_0 -x 146 -y 37 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 97 -y 110 -width 43 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd83 \
        -in $site_3_0 -x 83 -y 86 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd84 \
        -in $site_3_0 -x 120 -y 86 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd85 \
        -in $site_3_0 -x 157 -y 86 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd86 \
        -in $site_3_0 -x 60 -y 110 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd87 \
        -in $site_3_0 -x 145 -y 110 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd88 \
        -in $site_3_0 -x 59 -y 134 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd89 \
        -in $site_3_0 -x 98 -y 133 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    place $site_3_0.cpd90 \
        -in $site_3_0 -x 139 -y 133 -width 34 -height 19 -anchor nw \
        -bordermode ignore 
    checkbutton $top.che69 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -justify left \
        -text Reread -variable runZMC_reread 
    vTcl:DefineAlias "$top.che69" "Checkbutton1" vTcl:WidgetProc "$top" 1
    checkbutton $top.che77 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -justify left \
        -text {Use Modwave} -variable runZMC_modwave 
    vTcl:DefineAlias "$top.che77" "Checkbutton2" vTcl:WidgetProc "$top" 1
    entry $top.cpd81 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable QAMP 
    vTcl:DefineAlias "$top.cpd81" "Entry19" vTcl:WidgetProc "$top" 1
    checkbutton $top.che91 \
        -activebackground {#f4bcb2} -activeforeground {#000000} \
        -background wheat -disabledforeground {#a3a3a3} -foreground {#000000} \
        -highlightbackground wheat -highlightcolor black -justify left \
        -text {output 
diffuse} -variable ZMC_option_diffuse 
    vTcl:DefineAlias "$top.che91" "Checkbutton3" vTcl:WidgetProc "$top" 1
    label $top.lab37 \
        -background wheat -disabledforeground {#a3a3a3} -foreground {#000000} \
        -text {Occupancy filename} 
    vTcl:DefineAlias "$top.lab37" "Label22" vTcl:WidgetProc "$top" 1
    entry $top.ent38 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -insertbackground black \
        -textvariable ZMC_occ_fname 
    vTcl:DefineAlias "$top.ent38" "Entry28" vTcl:WidgetProc "$top" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but34 \
        -in $top -x 10 -y 410 -width 278 -height 30 -anchor nw \
        -bordermode ignore 
    place $top.but35 \
        -in $top -x 540 -y 410 -anchor nw -bordermode ignore 
    place $top.lab36 \
        -in $top -x 152 -y 16 -width 273 -height 27 -anchor nw \
        -bordermode ignore 
    place $top.fra37 \
        -in $top -x 20 -y 130 -width 155 -height 225 -anchor nw \
        -bordermode ignore 
    place $top.tex42 \
        -in $top -x 294 -y 310 -width 294 -height 76 -anchor nw \
        -bordermode ignore 
    place $top.but43 \
        -in $top -x 299 -y 410 -width 61 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.fra61 \
        -in $top -x 20 -y 50 -width 155 -height 75 -anchor nw \
        -bordermode ignore 
    place $top.fra68 \
        -in $top -x 185 -y 100 -width 195 -height 165 -anchor nw \
        -bordermode ignore 
    place $top.che69 \
        -in $top -x 367 -y 409 -width 67 -height 32 -anchor nw \
        -bordermode ignore 
    place $top.che77 \
        -in $top -x 188 -y 74 -width 107 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.cpd81 \
        -in $top -x 283 -y 162 -width 44 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.che91 \
        -in $top -x 440 -y 410 -width 77 -height 32 -anchor nw \
        -bordermode ignore 
    place $top.lab37 \
        -in $top -x 187 -y 51 -width 111 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.ent38 \
        -in $top -x 300 -y 51 -width 144 -height 19 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top34

